# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 429fcdc588ffb4e7ba5eafc602d3d560b7a019804c82d2aa81bf4af7e99e6d9f760426140f58fe4265287a5a15023014c4d26be6476cd85e7bc0d57f5fbe94eb

test:
  secret_key_base: 33152d8b80d340cba28a68022763f10c759203f1916db14b2ec78d3037b9406a77f319bf6d1817de694a0f2f6d01144c3db927a5da4b2514f2585b097f35cd51

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
